name: ${projectName}
version: ${projectVersion}
author: ${projectAuthor}
description: ${projectDescription}
softdepend: [ProtocolLib, VentureChat, SuperVanish, PuerkasChat, PlaceholderAPI, CarbonChat]

main: ${projectEntry}
api-version: 1.13

commands:
  commandprompter:
    aliases: [cmdprompter, cmdp]
    description: General CommandPrompter commands
  consoledelegate:
    aliases: [cdelegate]
    permission: commandprompter.consoledelegate
    description: Delegate command to console

permissions:
  commandprompter.reload:
    description: Allow sender to reload plugin.
  commandprompter.use:
    description: Allow sender to use CommandPrompter argument feature.
  commandprompter.cancel:
    description: Allow sender to cancel their own command completion.
  commandprompter.consoledelegate:
    description: Allow sender to delegate command to console.