name: CommandPrompter
version: ${pluginVersion}
author: CyRien
description: Perfect plugin companion for DeluxeMenus and ChestCommands

main: com.cyr1en.cp.CommandPrompter
api-version: 1.13

commands:
  commandprompter:
    aliases:
      - cp
      - cmdprompter
      - cmdprmptr
      - cmdp
    description: General CommandPrompter commands

permissions:
  commandprompter.reload:
    description: Allow sender to reload plugin.
  commandprompter.use:
    description: Allow sender to use CommandPrompter argument feature.