name: ${projectName}
version: ${projectVersion}
author: ${projectAuthor}
description: ${projectDescription}
softdepend: [ProtocolLib, VentureChat, SuperVanish, PuerkasChat, PlaceholderAPI]

main: ${projectEntry}
api-version: 1.13

commands:
  commandprompter:
    aliases: [cmdprompter, cmdp]
    description: General CommandPrompter commands

permissions:
  commandprompter.reload:
    description: Allow sender to reload plugin.
  commandprompter.use:
    description: Allow sender to use CommandPrompter argument feature.
  commandprompter.cancel:
    description: Allow sender to cancel their own command completion.