name: ${projectName}
version: ${projectVersion}
author: ${projectAuthor}
description: ${projectDescription}
softdepend: [SuperVanish, PlaceholderAPI, CarbonChat, Towny, PlaceholderAPI]

main: ${projectEntry}
api-version: 1.13

permissions:
  commandprompter.reload:
    description: Allow sender to reload plugin.
  commandprompter.use:
    description: Allow sender to use CommandPrompter argument feature.
  commandprompter.cancel:
    description: Allow sender to cancel their own command completion.
  commandprompter.consoledelegate:
    description: Allow sender to delegate command to console.
  commandprompter.rebuildheadcache:
    description: Allow sender to rebuild head cache.