package dev.cyr1en.promptcore.logic.transform;

/** Machine-readable error codes for transformation and template compilation failures. */
public enum TransformErrorCode {
  TEMPLATE_TOO_LONG,
  MALFORMED_TEMPLATE,
  MALFORMED_ESCAPE,
  MALFORMED_PLACEHOLDER,
  UNKNOWN_TRANSFORMER,
  CHAINED_TRANSFORMER,
  MALFORMED_TRANSFORMER_ARGUMENT,
  INPUT_TOO_LONG,
  OUTPUT_TOO_LONG,
  CONTROL_CHARACTER_DETECTED,
  NON_NUMERIC_INPUT,
  MATH_EXPRESSION_TOO_LONG,
  TOO_MANY_OPERATIONS,
  MATH_SYNTAX_ERROR,
  MAGNITUDE_EXCEEDED,
  DIVISION_BY_ZERO,
  MISSING_BINDING
}
