package dev.cyr1en.promptpaper.execution.postaction.template;

/**
 * Machine-readable error codes for action template compilation and rendering failures.
 */
public enum ActionTemplateErrorCode {
    SOURCE_TOO_LONG,
    CONTROL_CHARACTER_DETECTED,
    TOO_MANY_SEGMENTS,
    TOO_MANY_REFERENCES,
    MALFORMED_TEMPLATE,
    MALFORMED_ESCAPE,
    MALFORMED_PLACEHOLDER,
    UNKNOWN_TRANSFORMER,
    CHAINED_TRANSFORMER,
    MALFORMED_TRANSFORMER_ARGUMENT,
    MISSING_BINDING,
    PAPI_RESOLVER_MISSING,
    PAPI_RESOLUTION_FAILED,
    PAPI_VALUE_TOO_LONG,
    PAPI_CONTROL_CHARACTER,
    INPUT_TOO_LONG,
    OUTPUT_TOO_LONG,
    NON_NUMERIC_INPUT,
    MATH_EXPRESSION_TOO_LONG,
    TOO_MANY_OPERATIONS,
    MATH_SYNTAX_ERROR,
    MAGNITUDE_EXCEEDED,
    DIVISION_BY_ZERO
}
