name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up JDK
      uses: actions/setup-java@v2.5.0
      with:
        distribution: temurin
        java-version: 16
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Publish to Kakuno
      env:
        KAKUNO_USER: ${{ secrets.KAKUNO_USER }}
        KAKUNO_TOKEN: ${{ secrets.KAKUNO_TOKEN }}
      run: ./gradlew publish
    - name: Upload artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: CommandPrompter
        path: build/libs
